network:
  version: 2
  ethernets:
    ens33:
      dhcp4: false
      addresses:
        - 192.168.2.1/29
      gateway4: 192.168.2.2
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
